services:
  - type: web
    name: mazejs
    env: static
    buildCommand: ""
    publish: ./
    headers:
      - path: /*
        name: Cross-Origin-Opener-Policy
        value: same-origin
      - path: /*
        name: Cross-Origin-Embedder-Policy
        value: require-corp
      - path: /*
        name: Access-Control-Allow-Origin
        value: '*'
