services:
  - type: web
    name: maze-js
    runtime: static
    staticPublish: .
    headers:
      - path: /*
        name: Cross-Origin-Opener-Policy
        value: same-origin
      - path: /*
        name: Cross-Origin-Embedder-Policy
        value: require-corp
      - path: /*
        name: Access-Control-Allow-Origin
        value: '*'
